#ifndef UTILS
#define UTILS

#define PAHO_ERR_NOT_INIT -1000
#define PAHO_ERR_NOT_INITIALIZED_ONCE -1010
#define PAHO_ERR_ALREADY_CONNECTED -1011
#define PAHO_ERR_NOT_CONNECTED -1012

enum PahoLogLevel {
	PAHO_LOG_INFO,
	PAHO_LOG_NOTICE,
	PAHO_LOG_WARNING,
	PAHO_LOG_ERR,
	PAHO_LOG_DEBUG
};

#endif //UTILS
